version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: phyna_postgres_prod
    restart: always
    environment:
      POSTGRES_DB: wig_shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend-Spring
    container_name: phyna_backend_prod
    restart: always
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/wig_shop_db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      FLUTTERWAVE_SECRET_KEY: ${FLUTTERWAVE_SECRET_KEY}
      FLUTTERWAVE_PUBLIC_KEY: ${FLUTTERWAVE_PUBLIC_KEY}
      FLUTTERWAVE_REDIRECT_URL: ${FLUTTERWAVE_REDIRECT_URL}
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./Frontend-ReactJS
    container_name: phyna_frontend_prod
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_prod_data: